//! Build-time skills auto-discovery.
//!
//! WHY: the bundled "default skills" used to be a hand-maintained array in
//! `src/state/manifest.rs` (`DEFAULT_SKILL_FILES`). Every new skill markdown file
//! under `skills/` had to be added to that array by hand, so the list drifted —
//! `skills/assistant/morning_briefing.md` existed on disk but was never registered.
//! The headline ask is: "Add a skills folder where we place all available skills. A
//! utility reads all skills + descriptions to maintain the list." This build script
//! IS that utility: it walks `skills/` at build time and codegens the
//! `(relative_path, file_contents)` list so that dropping a new `*.md` into `skills/`
//! is enough — no source edit is ever required again.
//!
//! HOW: we recursively collect every `*.md` file under `skills/`, then emit a Rust
//! source file into `OUT_DIR` defining a `&[(&str, &str)]` slice. Each entry pairs
//! the repo-relative path (e.g. `"skills/assistant/morning_briefing.md"`, the same
//! shape the parser/source_path logic already expects) with an `include_str!` of the
//! file's *absolute* path. We intentionally use `include_str!` rather than baking the
//! escaped contents into the generated source: `include_str!` makes the compiler
//! itself track the dependency and re-read the live file, and it keeps the generated
//! file tiny and trivially correct regardless of what characters a skill body holds.
//!
//! `src/state/manifest.rs` consumes this via
//! `include!(concat!(env!("OUT_DIR"), "/skills_generated.rs"))` and feeds each pair to
//! the existing `skill_from_markdown` parser — parsing is NOT reinvented here.
//!
//! Platform note: build scripts always run on the host (never wasm) and this one is
//! std-only, matching the "core/state are platform-free, build.rs is std-only" rule.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // `CARGO_MANIFEST_DIR` is the crate root — the only stable anchor for locating the
    // content directories regardless of where cargo is invoked from.
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));

    // Both `skills/` and `agents/` are folder-driven: dropping a new `*.md` in either
    // registers it automatically, no source edit. Same walk+codegen for each — agents
    // used to be a hand-maintained `DEFAULT_AGENT_FILES` array in manifest.rs that
    // silently drifted (it omitted `assistant.md`); this build script is the single
    // "read all files from the folder, don't hardcode" utility for both kinds.
    gen_dir(
        &manifest_dir,
        &out_dir,
        "skills",
        "GENERATED_SKILL_FILES",
        "skills_generated.rs",
    );
    gen_dir(
        &manifest_dir,
        &out_dir,
        "agents",
        "GENERATED_AGENT_FILES",
        "agents_generated.rs",
    );
}

/// Walk `<manifest_dir>/<dir>` for `*.md` files and codegen a
/// `pub static <static_name>: &[(&str, &str)]` slice into `<out_dir>/<out_file>`.
///
/// Each entry pairs the repo-relative path (the same `dir/...` shape the parsers key
/// off) with an `include_str!` of the absolute path, so the compiler tracks each file
/// as a dependency and re-reads the live contents. Files sort by path: a numeric
/// filename prefix (e.g. `1_orchestrator.md`, `2_planner.md`) therefore gives authors
/// explicit, dynamic ordering of the registered set without any code change.
fn gen_dir(manifest_dir: &Path, out_dir: &Path, dir: &str, static_name: &str, out_file: &str) {
    let root = manifest_dir.join(dir);

    // Re-run codegen whenever the directory structure changes (a file is added or
    // removed). Per-file `rerun-if-changed` lines are emitted below so edits to an
    // existing file body also re-trigger the build.
    println!("cargo:rerun-if-changed={dir}");

    let mut md_files: Vec<PathBuf> = Vec::new();
    collect_markdown(&root, &mut md_files);

    // Deterministic order so the generated source — and therefore the registered
    // order — is stable across builds and machines (and honors numeric prefixes).
    md_files.sort();

    let mut generated = String::new();
    generated.push_str(&format!(
        "// @generated by build.rs — do not edit. Source: the `{dir}/` directory.\n\
         // Each entry is (repo-relative path, file contents). Regenerated whenever a\n\
         // `*.md` file under `{dir}/` is added, removed, or edited.\n"
    ));
    generated.push_str(&format!("pub static {static_name}: &[(&str, &str)] = &[\n"));

    for path in &md_files {
        // Tell cargo to re-run if this specific file's contents change.
        println!("cargo:rerun-if-changed={}", path.display());

        let rel = path
            .strip_prefix(manifest_dir)
            .unwrap_or(path)
            .to_string_lossy()
            // Normalize to forward slashes so the embedded `source_path` is identical
            // on Windows and Unix (the rest of the app keys off `dir/...` paths).
            .replace('\\', "/");

        let abs = path.to_string_lossy().replace('\\', "/");

        // `include_str!` takes a string literal; both `rel` and `abs` are filesystem
        // paths we control. The `{:?}` (Debug) formatter emits a properly escaped Rust
        // string literal, so any unusual characters in a path are handled correctly.
        generated.push_str(&format!("    ({rel:?}, include_str!({abs:?})),\n"));
    }

    generated.push_str("];\n");

    let out_path = out_dir.join(out_file);
    fs::write(&out_path, generated)
        .unwrap_or_else(|err| panic!("failed to write generated {dir} list: {err}"));
}

/// Recursively collect every `*.md` file under `dir` into `out`.
///
/// A missing `skills/` directory is treated as "no skills" rather than a hard error,
/// so the crate still builds in a checkout where the folder was removed (the runtime
/// falls back to an empty default skill set, same as before).
fn collect_markdown(dir: &Path, out: &mut Vec<PathBuf>) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(_) => return,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_markdown(&path, out);
        } else if path.extension().and_then(|ext| ext.to_str()) == Some("md") {
            out.push(path);
        }
    }
}
