import { describe, expect, test } from 'bun:test'
import { Workspace } from '../../../src/backend/files/Workspace.js'
import { MemoryRepository } from '../../../src/backend/repositories/MemoryRepository.js'
import { AgentCatalogue } from '../../../src/core/agent/AgentCatalogue.js'
import { resolveTools } from '../../../src/core/agent/loadAgent.js'
import { Outcome } from '../../../src/core/Outcome.js'
import { Blocked } from '../../../src/core/tools/HttpPort.js'
import { BUILTIN_TOOLS } from '../../../src/core/tools/index.js'
import { Toolbox } from '../../../src/core/tools/Toolbox.js'

/**
 * That the tools are actually attached, from the real agent file.
 *
 * This tree's signature defect, nine times over, is a capability that was built
 * and never named — and the named-and-not-wired half is worse, because the code
 * is all there and the only thing missing is one word in a list. Every test
 * beside this one constructs the tool itself, so all of them stayed green while
 * `tools:` in `agents/main/agent.md` said nothing about `search` or `fetch`.
 *
 * So this reads the real file through the real `AgentCatalogue` — the same path
 * the browser and `scripts/dryrun.js` take — and drives the resolved toolbox.
 * A `file://` fetch, which is not a network: the roster on disk is the roster
 * the build publishes, and the point is precisely to assert against what ships
 * rather than against a fixture that agrees with the test.
 */

/** A port that records what it was handed. */
function fakePort() {
  const calls = []
  const port = async (request) => {
    calls.push(request)
    return Outcome.ok({
      url: request.url,
      status: 200,
      contentType: 'text/plain',
      text: 'a real answer',
      bytes: 13,
      truncated: false,
      stopped: '',
      blocked: Blocked.NONE,
    })
  }
  port.calls = calls
  return port
}

const catalogue = new AgentCatalogue(new URL('../../..', import.meta.url).href.replace(/\/$/, ''))

/**
 * The same catalogue over `public/`, which is where the ROSTER is.
 *
 * A directory cannot be listed over HTTP, so `index.json` is generated by
 * `scripts/agents.js` and exists only in the published copy — `catalogue` above
 * can read any agent by name and cannot answer who exists. Reading the roster
 * from the published tree is the honest thing anyway: it is what the browser
 * fetches, and a `public/` left stale by an edit to `agents/` is a deploy that
 * ships an agent nobody sees. If these turn red after editing an agent file,
 * run `bun run agents`.
 */
const published = new AgentCatalogue(
  new URL('../../../public', import.meta.url).href.replace(/\/$/, ''),
)

describe('the tools the real agent file asks for', () => {
  test('main names search and fetch, and both reach the port they were composed with', async () => {
    const spec = await catalogue.spec('main')
    expect(spec.ok).toBe(true)

    const http = fakePort()
    // The peers as well, because `main` now names one: `researcher`. Without
    // them this resolves five tools and one note, and the note is the whole
    // finding — a `tools:` entry that resolves to nothing is exactly the defect
    // this file exists to catch, in the other direction.
    const roster = await published.all()
    const peers = roster.value.filter((peer) => peer.name !== spec.value.name)
    const resolved = resolveTools({
      names: spec.value.tools,
      peers,
      dispatch: async () => Outcome.ok('delegated'),
      services: { http, sandbox: null },
    })
    const toolbox = new Toolbox(resolved.value)

    // Named in the file at all. Deleting either from `tools:` turns this red,
    // which is the only thing in the tree that notices.
    expect(toolbox.names).toContain('search')
    expect(toolbox.names).toContain('fetch')
    expect(resolved.notes).toEqual([])

    // And WIRED: the port handed to `resolveTools` is the one the tool used.
    // A tool that is named but composed without its collaborator answers
    // politely and reaches nothing, which no name check can see.
    const said = await toolbox.run('fetch({"url": "https://example.com/"})')
    expect(said.count).toBe(1)
    expect(http.calls).toHaveLength(1)
    expect(http.calls[0].url).toBe('https://example.com/')
    expect(said.observation).toContain('a real answer')

    const searched = await toolbox.run('search({"query": "zig"})')
    expect(http.calls).toHaveLength(2)
    expect(http.calls[1].method).toBe('POST')
    expect(searched.observation).not.toContain('there is no tool called')
  })

  test('main names read_file and write_file, and both reach the store it was composed with', async () => {
    // Same argument as the test above, for the capability the goal is made of.
    // A file store that is built, tested and absent from `tools:` is a store
    // the agent cannot reach, and every other test of it constructs the tool
    // itself and would stay green through exactly that.
    const spec = await catalogue.spec('main')
    const files = new Workspace(new MemoryRepository('File'))

    const resolved = resolveTools({ names: spec.value.tools, services: { files } })
    const toolbox = new Toolbox(resolved.value)

    expect(toolbox.names).toContain('read_file')
    expect(toolbox.names).toContain('write_file')

    const wrote = await toolbox.run('write_file({"path": "notes.md", "content": "kept"})')
    expect(wrote.observation).toContain('wrote notes.md, 4 bytes')
    // Through the real store and back out, so a tool wired to `NO_FILES` by a
    // missing key in the services object fails here rather than answering
    // politely for ever.
    expect((await files.read('notes.md')).value.text).toBe('kept')
    expect((await toolbox.run('read_file({"path": "notes.md"})')).observation).toContain('kept')
  })
})

describe('the peer the real agent file asks for', () => {
  /**
   * `agentWorker.js` was the one realm on the architecture's diagram that
   * nothing had ever entered, and the reason was one word: the roster held a
   * single agent, so `ChatService` computed no peers, so no `tools:` entry could
   * ever resolve to one and the pool was never asked for a thread. This asserts
   * the wiring end to end at the layer where it broke — the real roster, the
   * real files, the real resolver — and turns red if either half is undone.
   */
  test('main names researcher, and it resolves to a call that reaches the dispatcher', async () => {
    const spec = await catalogue.spec('main')
    const roster = await published.all()
    expect(roster.value.map((peer) => peer.name)).toContain('researcher')

    const asked = []
    const resolved = resolveTools({
      names: spec.value.tools,
      peers: roster.value.filter((peer) => peer.name !== spec.value.name),
      dispatch: async (name, task) => {
        asked.push({ name, task })
        return Outcome.ok('a paragraph and three URLs')
      },
    })
    const toolbox = new Toolbox(resolved.value)
    expect(toolbox.names).toContain('researcher')

    const said = await toolbox.run('researcher({"task": "what is the latest Zig release?"})')
    expect(asked).toEqual([{ name: 'researcher', task: 'what is the latest Zig release?' }])
    expect(said.observation).toContain('a paragraph and three URLs')
  })

  /**
   * The description a calling model reads is the peer's OWN, off its own file.
   * A sub-agent tool whose description is generated — "Ask the researcher
   * agent." — tells the model nothing about when to ask it, and that generated
   * line is what `SubAgentTool` falls back to when a file has no description.
   */
  test('the line the calling model reads is the researcher file’s own description', async () => {
    const roster = await published.all()
    const researcher = roster.value.find((peer) => peer.name === 'researcher')
    const resolved = resolveTools({
      names: ['researcher'],
      peers: [researcher],
      dispatch: async () => Outcome.ok(''),
    })
    const rendered = new Toolbox(resolved.value).render()
    expect(rendered).toContain(researcher.description)
    expect(rendered).not.toContain('Ask the researcher agent.')
  })
})

/**
 * Reading back work that was handed over.
 *
 * The split this tool exists for: WHICH tasks exist and whether they are done
 * is a fact and lives in the context block, so this tool spends its round trip
 * on the one thing a prompt cannot afford to carry — what a finished task
 * actually said.
 */
describe('check_task', () => {
  const port = (tasks) => ({
    list: () => tasks,
    get: (id) => tasks.find((task) => task.id === id) ?? null,
  })

  const finished = {
    id: 't1',
    agent: 'researcher',
    task: 'read it',
    state: 'done',
    startedAt: 1000,
    endedAt: 4000,
    progress: null,
    result: { ok: true, value: 'the page said hello', failure: null, notes: [] },
  }

  test('a finished task comes back with the answer, which the prompt never carries', async () => {
    const tool = BUILTIN_TOOLS.check_task({ tasks: port([finished]) })

    const said = await tool.call({ id: 't1' })

    expect(said.value).toContain('the page said hello')
    expect(said.value).toContain('3s')
  })

  test('a running task is reported, not waited for', async () => {
    const running = {
      ...finished,
      id: 't2',
      state: 'running',
      endedAt: 0,
      progress: { doing: ['fetch'] },
      result: null,
    }
    const tool = BUILTIN_TOOLS.check_task({ tasks: port([running]) })

    const said = await tool.call({ id: 't2' })

    expect(said.value).toContain('still working')
    expect(said.value).toContain('fetch')
  })

  test('an id that is not there lists the ones that are, rather than failing', async () => {
    const tool = BUILTIN_TOOLS.check_task({ tasks: port([finished]) })

    const said = await tool.call({ id: 'nope' })

    expect(said.ok).toBe(true)
    expect(said.value).toContain('t1')
  })

  test('a build with no task port answers instead of throwing', async () => {
    const said = await BUILTIN_TOOLS.check_task({}).call({ id: 't1' })
    expect(said.ok).toBe(true)
    expect(said.value).toContain('not handed any work over')
  })
})
