// Generates `libs.generated.js` (gitignored): the TypeScript default-library
// `.d.ts` files embedded as strings, keyed the way @typescript/vfs expects
// ("/lib.es2022.d.ts" ...). Embedding the libs makes the worker bundle fully
// offline — no runtime CDN fetches.
//
// Only the libs the worker's compilerOptions reference are embedded: we walk
// the `/// <reference lib="..." />` directives transitively from the seed
// libs below, so the list tracks whatever TypeScript version is installed
// instead of being hand-maintained. Run via `bun run build` (see package.json).

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const libDir = join(dirname(require.resolve("typescript/package.json")), "lib");

// Seeds = the `lib` entries in entry.js's COMPILER_OPTIONS, plus the default
// lib file for target ES2022 (lib.es2022.full.d.ts) since hosts may still ask
// for it. Everything they reference is pulled in transitively.
const SEEDS = [
  "lib.es2022.d.ts",
  "lib.es2022.full.d.ts",
  "lib.dom.d.ts",
  "lib.dom.iterable.d.ts",
];

const collected = new Map();
const queue = [...SEEDS];
while (queue.length > 0) {
  const name = queue.shift();
  if (collected.has(name)) continue;
  const text = readFileSync(join(libDir, name), "utf8");
  collected.set(name, text);
  for (const match of text.matchAll(
    /\/\/\/\s*<reference\s+lib="([^"]+)"\s*\/>/g,
  )) {
    queue.push(`lib.${match[1]}.d.ts`);
  }
}

let src =
  "// Generated by gen-libs.mjs — do not edit, do not commit.\n" +
  "// Map of \"/lib.*.d.ts\" -> file text for @typescript/vfs.\n" +
  "export const libFiles = new Map([\n";
for (const [name, text] of collected) {
  src += `  [${JSON.stringify(`/${name}`)}, ${JSON.stringify(text)}],\n`;
}
src += "]);\n";

writeFileSync(new URL("./libs.generated.js", import.meta.url), src);
console.log(`gen-libs: embedded ${collected.size} lib files from ${libDir}`);
