//! The agents FOLDER decides the baked config: every `agents/*.md` (and
//! `agents/skills/*.md`) is embedded, no code change to add an agent.
//! `agents/manifest.json` (optional) fixes the order; the rest follows
//! alphabetically. The wasm boot can override the whole set at runtime by
//! fetching the same manifest from the served site root.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn md_files(dir: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = fs::read_dir(dir)
        .map(|entries| {
            entries
                .filter_map(Result::ok)
                .map(|e| e.path())
                .filter(|p| p.extension().is_some_and(|x| x == "md"))
                .collect()
        })
        .unwrap_or_default();
    files.sort();
    files
}

/// Order from `manifest.json`'s "agents" array (filenames), unlisted after.
fn apply_manifest_order(dir: &Path, files: &mut [PathBuf]) {
    let Ok(text) = fs::read_to_string(dir.join("manifest.json")) else {
        return;
    };
    let Ok(value) = text.parse::<serde_json::Value>() else {
        return;
    };
    let listed: Vec<String> = value["agents"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();
    files.sort_by_key(|p| {
        let name = p.file_name().unwrap_or_default().to_string_lossy();
        listed
            .iter()
            .position(|l| l == name.as_ref())
            .unwrap_or(usize::MAX)
    });
}

fn push_entries(out: &mut String, name: &str, root: &Path, files: &[PathBuf]) {
    let _ = writeln!(out, "pub const {name}: &[(&str, &str)] = &[");
    for file in files {
        let rel = file.strip_prefix(root).unwrap_or(file);
        let label = format!("agents/{}", rel.display());
        let _ = writeln!(out, "    ({label:?}, include_str!({:?})),", file.display());
    }
    let _ = writeln!(out, "];");
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let agents_dir = manifest_dir.join("../../agents").canonicalize().unwrap();
    println!("cargo:rerun-if-changed={}", agents_dir.display());

    let mut agent_files = md_files(&agents_dir);
    agent_files.retain(|p| p.file_name().is_some_and(|n| n != "soul.md"));
    apply_manifest_order(&agents_dir, &mut agent_files);
    let skill_files = md_files(&agents_dir.join("skills"));

    let mut out = String::from("// generated by build.rs — the agents/ folder is the config\n");
    push_entries(&mut out, "AGENT_FILES", &agents_dir, &agent_files);
    push_entries(&mut out, "SKILL_FILES", &agents_dir, &skill_files);
    let _ = writeln!(
        out,
        "pub const SOUL_MD: &str = include_str!({:?});",
        agents_dir.join("soul.md").display()
    );

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("agents_gen.rs");
    fs::write(dest, out).unwrap();
}
