//! The agents FOLDER decides the baked config: every `agents/*.md` (and
//! `agents/skills/*.md`) is embedded, no code change to add an agent.
//! `agents/manifest.json` (optional) fixes the order; the rest follows
//! alphabetically. The wasm boot can override the whole set at runtime by
//! fetching the same manifest from the served site root.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// Every `*.md` under `dir`, RECURSIVELY — a subfolder is a team of agents,
/// so `agents/coding/coder.md` is discovered the same as a top-level agent.
fn md_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        let Ok(entries) = fs::read_dir(&d) else {
            continue;
        };
        for path in entries.filter_map(Result::ok).map(|e| e.path()) {
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|x| x == "md") {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

/// Order from `manifest.json`'s "agents" array (filenames), unlisted after.
fn apply_manifest_order(dir: &Path, files: &mut [PathBuf]) {
    let Ok(text) = fs::read_to_string(dir.join("manifest.json")) else {
        return;
    };
    let Ok(value) = text.parse::<serde_json::Value>() else {
        return;
    };
    let listed: Vec<String> = value["agents"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();
    files.sort_by_key(|p| {
        let name = p.file_name().unwrap_or_default().to_string_lossy();
        listed
            .iter()
            .position(|l| l == name.as_ref())
            .unwrap_or(usize::MAX)
    });
}

fn push_entries(out: &mut String, name: &str, root: &Path, files: &[PathBuf]) {
    let _ = writeln!(out, "pub const {name}: &[(&str, &str)] = &[");
    for file in files {
        let rel = file.strip_prefix(root).unwrap_or(file);
        let label = format!("agents/{}", rel.display());
        let _ = writeln!(out, "    ({label:?}, include_str!({:?})),", file.display());
    }
    let _ = writeln!(out, "];");
}

/// Manifest-listed custom JS tools (filename, source) → `(name, source)`.
fn manifest_tools(dir: &Path) -> Vec<(String, PathBuf)> {
    let Ok(text) = fs::read_to_string(dir.join("manifest.json")) else {
        return Vec::new();
    };
    let Ok(value) = text.parse::<serde_json::Value>() else {
        return Vec::new();
    };
    value["tools"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|v| v.as_str())
                .map(|f| {
                    let name = f.strip_suffix(".js").unwrap_or(f).to_string();
                    (name, dir.join(f))
                })
                .collect()
        })
        .unwrap_or_default()
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    // The agents folder lives UNDER assets/ so the same files are both baked
    // (fallback) AND served verbatim at `/assets/agents/*` for runtime load.
    let agents_dir = manifest_dir.join("assets/agents").canonicalize().unwrap();
    println!("cargo:rerun-if-changed={}", agents_dir.display());

    // Agents = every md under the folder tree EXCEPT soul.md, team.md files
    // (a folder's team declaration, wave-16), README.md (folder docs) and
    // anything under skills/. A subfolder is a team; nested agents are
    // discovered too.
    let skills_dir = agents_dir.join("skills");
    let all = md_files(&agents_dir);
    let mut agent_files: Vec<PathBuf> = all
        .iter()
        .filter(|p| {
            p.file_name()
                .is_some_and(|n| n != "soul.md" && n != "team.md" && n != "README.md")
        })
        .filter(|p| !p.starts_with(&skills_dir))
        .cloned()
        .collect();
    apply_manifest_order(&agents_dir, &mut agent_files);
    let team_files: Vec<PathBuf> = all
        .iter()
        .filter(|p| p.file_name().is_some_and(|n| n == "team.md"))
        .cloned()
        .collect();
    let skill_files = md_files(&skills_dir);

    let mut out = String::from("// generated by build.rs — the agents/ folder is the config\n");
    push_entries(&mut out, "AGENT_FILES", &agents_dir, &agent_files);
    push_entries(&mut out, "TEAM_FILES", &agents_dir, &team_files);
    push_entries(&mut out, "SKILL_FILES", &agents_dir, &skill_files);
    let _ = writeln!(
        out,
        "pub const SOUL_MD: &str = include_str!({:?});",
        agents_dir.join("soul.md").display()
    );
    // Baked JS tools: (tool name, source) so host builds know the names and
    // wasm has a fallback if the live fetch misses.
    let _ = writeln!(out, "pub const TOOL_FILES: &[(&str, &str)] = &[");
    for (name, path) in manifest_tools(&agents_dir) {
        let _ = writeln!(out, "    ({name:?}, include_str!({:?})),", path.display());
    }
    let _ = writeln!(out, "];");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("agents_gen.rs");
    fs::write(dest, out).unwrap();
}
