#!/usr/bin/env bash
# Generates bench/acceptance/STATUS.md from the native acceptance lane.
# Hand edits to STATUS.md get overwritten — ROWS.md is the frozen definition.
set -euo pipefail
cd "$(dirname "$0")/.."

ok=1
out=$(cargo test -p askk-engine --test acceptance 2>&1) || ok=0
lines=$(printf '%s\n' "$out" | grep -E '^test [a-z0-9_]+ \.\.\.' || true)

{
  echo "# Acceptance status — GENERATED by scripts/bench-status.sh, $(date +%F)"
  echo
  if [ "$ok" = 1 ]; then
    echo "Native lane: **GREEN** (\`cargo test -p askk-engine --test acceptance\`)"
  else
    echo "Native lane: **RED**"
  fi
  echo
  echo '```'
  printf '%s\n' "$lines"
  echo '```'
  echo
  echo "Non-native rows (browser / blocked / manual) and per-row meaning:"
  echo "see ROWS.md — A4, A6, A8, A9, A10 red; A5/A7 foundation-only (row red)."
} > bench/acceptance/STATUS.md

[ "$ok" = 1 ] || { echo "acceptance lane RED"; exit 1; }
echo "bench/acceptance/STATUS.md refreshed"
